#!/bin/bash

clear

# Server side, to receive calls

#-----------------------------------------------------------------------
# Get the parameters from INI file

# INI file    
ini_file=/vagrant/ur_callmonit.ini

# Temporary config file used by PJSUA
pjsua_config=/vagrant/pjsua_conf.tmp

# Domain
domain=$(crudini --get $ini_file 'target' domain)
if [ $domain"empty" = "empty" ]; then
    echo ERROR: \"domain\" parameter is not defined in \"$ini_file\"
    exit 99
fi

# Target
target=$(crudini --get $ini_file 'target' target)
if [ $target"empty" = "empty" ]; then
    echo ERROR: \"target\" parameter is not defined in \"$ini_file\"
    exit 99
fi

# password
password=$(crudini --get $ini_file 'credential' $target)
if [ $password"empty" == "empty" ]; then
    echo ERROR: \"password\" for ext $target is not defined in \"$ini_file\"
    exit 99
fi

echo "# This file is auto-generated by ur_uas.sh" > $pjsua_config
echo "--app-log-level=3" >> $pjsua_config
echo "--log-level=3" >> $pjsua_config
echo "--local-port=5068" >> $pjsua_config
echo "--auto-answer 200" >> $pjsua_config
echo "--auto-loop" >> $pjsua_config
echo "--duration=1200" >> $pjsua_config
echo "--null-audio" >> $pjsua_config

# Account
echo "--realm $domain" >> $pjsua_config
echo "--registrar sip:$domain" >> $pjsua_config
echo "--proxy sip:$domain" >> $pjsua_config
echo "--id sip:$target"@"$domain" >> $pjsua_config
echo "--username $target" >> $pjsua_config
echo "--password $password" >> $pjsua_config  

echo "XXX"
cat $pjsua_config
echo "XXX"

read -p wait...

echo "================================================="
echo "= UAS - Call Receiver                           ="
# echo "= Receiver: "$receiver"@"$domain
echo "================================================="

# read -p "Press [Enter] key to continue to PJSUA..." key
#-----------------------------------------------------------------------

/home/vagrant/pjproject-2.7/pjsip-apps/bin/pjsua-x86_64-unknown-linux-gnu \
    --config-file $pjsua_config

#    --local-port=5068 \
#    --registrar sip:$domain \
#    --proxy sip:$domain \
#    --auto-answer 200 \
#    --auto-loop \
#    --duration=1200 \
#    --app-log-level=4 \
#    --log-level=4 \
#    --null-audio \
#    $pjsua_params 

    
#    --id sip:$receiver"@"$domain \
#     --realm \* \
#     --username $receiver \
#     --password $password \

#    --log-file=/vagrant/pjsua.log \
#    --auto-play \
#    --play-file=/vagrant/file02.wav \
#    --playback-dev=0 \
#    --dis-codec=speex/16000 \
#    --dis-codec=speex/8000 \
#    --dis-codec=speex/32000 \
#    --dis-codec=iLBC/8000 \
#    --dis-codec=GSM/8000 \
#    --dis-codec=G722/16000 \



#    --dis-codec=L16/44100 \
#    --dis-codec=L16/44100 \
   
#    
#    --capture-dev=-1 \
#    --auto-loop \ 


#List of audio codecs:
#    --dis-codec=PCMU/8000 
#    --dis-codec=PCMA/8000 
